export const vocabPart3 = [
  // ============================================================
  // LESSON 41: Emotions & Feelings (Unit 8: Advanced Topics)
  // ============================================================

  // --- Words (20 adjectives) ---
  { english: 'happy', romanized: 'desteña', amharic: 'ደስተኛ', category: 'word', lesson_id: 41, pronunciation_guide: null },
  { english: 'sad', romanized: 'azañ', amharic: 'አዘኝ', category: 'word', lesson_id: 41, pronunciation_guide: null },
  { english: 'angry', romanized: 'tenadaj', amharic: 'ተናዳጅ', category: 'word', lesson_id: 41, pronunciation_guide: null },
  { english: 'afraid', romanized: 'feri', amharic: 'ፈሪ', category: 'word', lesson_id: 41, pronunciation_guide: null },
  { english: 'tired', romanized: 'dekama', amharic: 'ደካማ', category: 'word', lesson_id: 41, pronunciation_guide: null },
  { english: 'surprised', romanized: 'yetegereme', amharic: 'የተገረመ', category: 'word', lesson_id: 41, pronunciation_guide: null },
  { english: 'excited', romanized: 'yetedesetew', amharic: 'የተደሰተ', category: 'word', lesson_id: 41, pronunciation_guide: null },
  { english: 'worried', romanized: 'yetesasbew', amharic: 'የተሳሰበ', category: 'word', lesson_id: 41, pronunciation_guide: null },
  { english: 'nervous', romanized: 'yetelawesew', amharic: 'የተላወሰ', category: 'word', lesson_id: 41, pronunciation_guide: null },
  { english: 'confused', romanized: 'yetegondayew', amharic: 'የተጎንዳየ', category: 'word', lesson_id: 41, pronunciation_guide: null },
  { english: 'proud', romanized: 'kuratam', amharic: 'ኩራተኛ', category: 'word', lesson_id: 41, pronunciation_guide: null },
  { english: 'ashamed', romanized: 'yeteshefeew', amharic: 'የተሸፈ', category: 'word', lesson_id: 41, pronunciation_guide: null },
  { english: 'grateful', romanized: 'ameseganyi', amharic: 'አመስጋኝ', category: 'word', lesson_id: 41, pronunciation_guide: null },
  { english: 'lonely', romanized: 'bilchgna', amharic: 'ብቸኛ', category: 'word', lesson_id: 41, pronunciation_guide: null },
  { english: 'bored', romanized: 'yeselechew', amharic: 'የሰለቸው', category: 'word', lesson_id: 41, pronunciation_guide: null },
  { english: 'calm', romanized: 'tsegiyu', amharic: 'ጸጥተኛ', category: 'word', lesson_id: 41, pronunciation_guide: null },
  { english: 'brave', romanized: 'defar', amharic: 'ደፋር', category: 'word', lesson_id: 41, pronunciation_guide: null },
  { english: 'kind', romanized: 'degg', amharic: 'ደግ', category: 'word', lesson_id: 41, pronunciation_guide: null },
  { english: 'patient', romanized: 'tagisgna', amharic: 'ታጋሽ', category: 'word', lesson_id: 41, pronunciation_guide: null },
  { english: 'jealous', romanized: 'qenateña', amharic: 'ቅናተኛ', category: 'word', lesson_id: 41, pronunciation_guide: null },

  // --- Phrases (20) ---
  { english: 'I am happy', romanized: 'desbitognal', amharic: 'ደስ ብሎኛል', category: 'phrase', lesson_id: 41, pronunciation_guide: null },
  { english: 'I am sad', romanized: 'azñeñal', amharic: 'አዝኜያለሁ', category: 'phrase', lesson_id: 41, pronunciation_guide: null },
  { english: 'He is angry', romanized: 'irsu tenaduwal', amharic: 'እርሱ ተናድዷል', category: 'phrase', lesson_id: 41, pronunciation_guide: null },
  { english: "Don't be afraid", romanized: 'atifra', amharic: 'አትፍራ', category: 'phrase', lesson_id: 41, pronunciation_guide: null },
  { english: 'I am tired', romanized: 'dekmoñal', amharic: 'ደክሞኛል', category: 'phrase', lesson_id: 41, pronunciation_guide: null },
  { english: 'I am surprised', romanized: 'ageremognal', amharic: 'አገረመኝ', category: 'phrase', lesson_id: 41, pronunciation_guide: null },
  { english: 'I am excited', romanized: 'destageñal', amharic: 'ደስ ታገኛለሁ', category: 'phrase', lesson_id: 41, pronunciation_guide: null },
  { english: "Don't worry", romanized: 'atesebaseb', amharic: 'አትሳሰብ', category: 'phrase', lesson_id: 41, pronunciation_guide: null },
  { english: 'I feel nervous', romanized: 'telawshalehu', amharic: 'ተላውሻለሁ', category: 'phrase', lesson_id: 41, pronunciation_guide: null },
  { english: 'I am confused', romanized: 'gondayeñal', amharic: 'ጎንዳየኝ', category: 'phrase', lesson_id: 41, pronunciation_guide: null },
  { english: 'I am proud of you', romanized: 'biante ikurallehu', amharic: 'ብአንተ እኮራለሁ', category: 'phrase', lesson_id: 41, pronunciation_guide: null },
  { english: 'I am ashamed', romanized: 'shefognal', amharic: 'ሸፍቆኛል', category: 'phrase', lesson_id: 41, pronunciation_guide: null },
  { english: 'I am grateful', romanized: 'ameseginalehu', amharic: 'አመሰግናለሁ', category: 'phrase', lesson_id: 41, pronunciation_guide: null },
  { english: 'I feel lonely', romanized: 'bilchgna yisemañal', amharic: 'ብቸኛ ይሰማኛል', category: 'phrase', lesson_id: 41, pronunciation_guide: null },
  { english: 'I am bored', romanized: 'selichoñal', amharic: 'ሰልቸኛል', category: 'phrase', lesson_id: 41, pronunciation_guide: null },
  { english: 'Be calm', romanized: 'tsegiyu hun', amharic: 'ጸጥ ብለህ ሁን', category: 'phrase', lesson_id: 41, pronunciation_guide: null },
  { english: 'He is brave', romanized: 'irsu defar new', amharic: 'እርሱ ደፋር ነው', category: 'phrase', lesson_id: 41, pronunciation_guide: null },
  { english: 'She is kind', romanized: 'irsua degg nat', amharic: 'እርሷ ደግ ናት', category: 'phrase', lesson_id: 41, pronunciation_guide: null },
  { english: 'Be patient', romanized: 'tagis', amharic: 'ታገስ', category: 'phrase', lesson_id: 41, pronunciation_guide: null },
  { english: "Don't be jealous", romanized: 'atiqina', amharic: 'አትቅና', category: 'phrase', lesson_id: 41, pronunciation_guide: null },

  // ============================================================
  // LESSON 42: Common Verbs Part 3 (Unit 8: Advanced Topics)
  // ============================================================

  // --- Words (20 verbs) ---
  { english: 'to cook', romanized: 'mabsel', amharic: 'ማብሰል', category: 'word', lesson_id: 42, pronunciation_guide: null },
  { english: 'to wash', romanized: 'mateb', amharic: 'ማጠብ', category: 'word', lesson_id: 42, pronunciation_guide: null },
  { english: 'to clean', romanized: 'matsdat', amharic: 'ማጽዳት', category: 'word', lesson_id: 42, pronunciation_guide: null },
  { english: 'to open', romanized: 'mekfet', amharic: 'መክፈት', category: 'word', lesson_id: 42, pronunciation_guide: null },
  { english: 'to close', romanized: 'mezgat', amharic: 'መዝጋት', category: 'word', lesson_id: 42, pronunciation_guide: null },
  { english: 'to carry', romanized: 'meshkem', amharic: 'መሸከም', category: 'word', lesson_id: 42, pronunciation_guide: null },
  { english: 'to push', romanized: 'megfat', amharic: 'መግፋት', category: 'word', lesson_id: 42, pronunciation_guide: null },
  { english: 'to pull', romanized: 'megotat', amharic: 'መጎተት', category: 'word', lesson_id: 42, pronunciation_guide: null },
  { english: 'to throw', romanized: 'mewerwer', amharic: 'መወርወር', category: 'word', lesson_id: 42, pronunciation_guide: null },
  { english: 'to break', romanized: 'mesber', amharic: 'መስበር', category: 'word', lesson_id: 42, pronunciation_guide: null },
  { english: 'to build', romanized: 'meseñat', amharic: 'መሥራት', category: 'word', lesson_id: 42, pronunciation_guide: null },
  { english: 'to cut', romanized: 'meqret', amharic: 'መቁረጥ', category: 'word', lesson_id: 42, pronunciation_guide: null },
  { english: 'to choose', romanized: 'memret', amharic: 'መምረጥ', category: 'word', lesson_id: 42, pronunciation_guide: null },
  { english: 'to begin', romanized: 'mejemer', amharic: 'መጀመር', category: 'word', lesson_id: 42, pronunciation_guide: null },
  { english: 'to finish', romanized: 'mechres', amharic: 'መጨረስ', category: 'word', lesson_id: 42, pronunciation_guide: null },
  { english: 'to help', romanized: 'merdat', amharic: 'መርዳት', category: 'word', lesson_id: 42, pronunciation_guide: null },
  { english: 'to teach', romanized: 'mastemar', amharic: 'ማስተማር', category: 'word', lesson_id: 42, pronunciation_guide: null },
  { english: 'to learn', romanized: 'memarir', amharic: 'መማር', category: 'word', lesson_id: 42, pronunciation_guide: null },
  { english: 'to send', romanized: 'melak', amharic: 'መላክ', category: 'word', lesson_id: 42, pronunciation_guide: null },
  { english: 'to receive', romanized: 'meqebel', amharic: 'መቀበል', category: 'word', lesson_id: 42, pronunciation_guide: null },

  // --- Phrases (20) ---
  { english: 'I am cooking', romanized: 'imibisallehu', amharic: 'እያበሰልሁ', category: 'phrase', lesson_id: 42, pronunciation_guide: null },
  { english: 'Wash the dishes', romanized: 'sahunu tateb', amharic: 'ሳህኑን ታጠብ', category: 'phrase', lesson_id: 42, pronunciation_guide: null },
  { english: 'Clean the room', romanized: 'kifilu atsda', amharic: 'ክፍሉን አጽዳ', category: 'phrase', lesson_id: 42, pronunciation_guide: null },
  { english: 'Open the book', romanized: 'metshafun kfet', amharic: 'መጽሐፉን ክፈት', category: 'phrase', lesson_id: 42, pronunciation_guide: null },
  { english: 'Close the door', romanized: 'berun zga', amharic: 'በሩን ዝጋ', category: 'phrase', lesson_id: 42, pronunciation_guide: null },
  { english: 'Carry this bag', romanized: 'yihin borsa shkem', amharic: 'ይህን ቦርሳ ሸክም', category: 'phrase', lesson_id: 42, pronunciation_guide: null },
  { english: 'Push the door', romanized: 'berun gfa', amharic: 'በሩን ግፋ', category: 'phrase', lesson_id: 42, pronunciation_guide: null },
  { english: 'Pull the rope', romanized: 'gemedun gotat', amharic: 'ገመዱን ጎትት', category: 'phrase', lesson_id: 42, pronunciation_guide: null },
  { english: 'Throw the ball', romanized: 'kuasu werwirew', amharic: 'ኳሱን ወርውር', category: 'phrase', lesson_id: 42, pronunciation_guide: null },
  { english: "Don't break it", romanized: 'atisbirew', amharic: 'አትስበረው', category: 'phrase', lesson_id: 42, pronunciation_guide: null },
  { english: 'Build a house', romanized: 'bet sera', amharic: 'ቤት ሥራ', category: 'phrase', lesson_id: 42, pronunciation_guide: null },
  { english: 'Cut the bread', romanized: 'dabon qret', amharic: 'ዳቦን ቁረጥ', category: 'phrase', lesson_id: 42, pronunciation_guide: null },
  { english: 'Choose one', romanized: 'andun mret', amharic: 'አንዱን ምረጥ', category: 'phrase', lesson_id: 42, pronunciation_guide: null },
  { english: "Let's begin", romanized: 'injemer', amharic: 'እንጀምር', category: 'phrase', lesson_id: 42, pronunciation_guide: null },
  { english: 'I finished', romanized: 'chersalehu', amharic: 'ጨርሻለሁ', category: 'phrase', lesson_id: 42, pronunciation_guide: null },
  { english: 'Please help me', romanized: 'irdañ', amharic: 'እርዳኝ', category: 'phrase', lesson_id: 42, pronunciation_guide: null },
  { english: 'She teaches children', romanized: 'ijochun tastemalech', amharic: 'ልጆችን ታስተምራለች', category: 'phrase', lesson_id: 42, pronunciation_guide: null },
  { english: 'I want to learn', romanized: 'memarir ifelligalehu', amharic: 'መማር እፈልጋለሁ', category: 'phrase', lesson_id: 42, pronunciation_guide: null },
  { english: 'Send a message', romanized: 'melikit laik', amharic: 'መልዕክት ላክ', category: 'phrase', lesson_id: 42, pronunciation_guide: null },
  { english: 'I received it', romanized: 'teqebelkut', amharic: 'ተቀብያለሁ', category: 'phrase', lesson_id: 42, pronunciation_guide: null },

  // ============================================================
  // LESSON 43: Daily Life Expressions (Unit 8: Advanced Topics)
  // ============================================================

  // --- Words (20 - mix of nouns, adverbs, adjectives) ---
  { english: 'morning', romanized: 'tewat', amharic: 'ጠዋት', category: 'word', lesson_id: 43, pronunciation_guide: null },
  { english: 'evening', romanized: 'misit', amharic: 'ምሽት', category: 'word', lesson_id: 43, pronunciation_guide: null },
  { english: 'tonight', romanized: 'zare mata', amharic: 'ዛሬ ማታ', category: 'word', lesson_id: 43, pronunciation_guide: null },
  { english: 'always', romanized: 'hulgizie', amharic: 'ሁልጊዜ', category: 'word', lesson_id: 43, pronunciation_guide: null },
  { english: 'never', romanized: 'befe', amharic: 'በፍጹም', category: 'word', lesson_id: 43, pronunciation_guide: null },
  { english: 'sometimes', romanized: 'andand gizie', amharic: 'አንዳንድ ጊዜ', category: 'word', lesson_id: 43, pronunciation_guide: null },
  { english: 'early', romanized: 'qedem', amharic: 'ቀደም', category: 'word', lesson_id: 43, pronunciation_guide: null },
  { english: 'late', romanized: 'zegay', amharic: 'ዘግይ', category: 'word', lesson_id: 43, pronunciation_guide: null },
  { english: 'ready', romanized: 'zegaju', amharic: 'ዘጋጁ', category: 'word', lesson_id: 43, pronunciation_guide: null },
  { english: 'busy', romanized: 'isiru', amharic: 'ዝብርቅርቅ', category: 'word', lesson_id: 43, pronunciation_guide: null },
  { english: 'problem', romanized: 'chigir', amharic: 'ችግር', category: 'word', lesson_id: 43, pronunciation_guide: null },
  { english: 'answer', romanized: 'meils', amharic: 'መልስ', category: 'word', lesson_id: 43, pronunciation_guide: null },
  { english: 'question', romanized: 'tiyaqe', amharic: 'ጥያቄ', category: 'word', lesson_id: 43, pronunciation_guide: null },
  { english: 'idea', romanized: 'hasab', amharic: 'ሃሳብ', category: 'word', lesson_id: 43, pronunciation_guide: null },
  { english: 'plan', romanized: 'iqid', amharic: 'ዕቅድ', category: 'word', lesson_id: 43, pronunciation_guide: null },
  { english: 'sure', romanized: 'irgiṭegna', amharic: 'እርግጠኛ', category: 'word', lesson_id: 43, pronunciation_guide: null },
  { english: 'maybe', romanized: 'minaibat', amharic: 'ምናልባት', category: 'word', lesson_id: 43, pronunciation_guide: null },
  { english: 'together', romanized: 'beyiberet', amharic: 'በጋራ', category: 'word', lesson_id: 43, pronunciation_guide: null },
  { english: 'alone', romanized: 'bichaye', amharic: 'ብቻዬ', category: 'word', lesson_id: 43, pronunciation_guide: null },
  { english: 'enough', romanized: 'beqi', amharic: 'በቂ', category: 'word', lesson_id: 43, pronunciation_guide: null },

  // --- Phrases (20) ---
  { english: 'Good morning', romanized: 'indemen aderu', amharic: 'እንደምን አደሩ', category: 'phrase', lesson_id: 43, pronunciation_guide: null },
  { english: 'Good evening', romanized: 'indemen amesu', amharic: 'እንደምን አመሹ', category: 'phrase', lesson_id: 43, pronunciation_guide: null },
  { english: 'See you tonight', romanized: 'zare mata inigebegñalen', amharic: 'ዛሬ ማታ እንገናኛለን', category: 'phrase', lesson_id: 43, pronunciation_guide: null },
  { english: 'I always wake up early', romanized: 'hulgizie qedem inekalehu', amharic: 'ሁልጊዜ ቀደም እነቃለሁ', category: 'phrase', lesson_id: 43, pronunciation_guide: null },
  { english: 'I never lie', romanized: 'befe alawiim', amharic: 'በፍጹም አላውቅም', category: 'phrase', lesson_id: 43, pronunciation_guide: null },
  { english: 'Sometimes I read', romanized: 'andand gizie inibilalehu', amharic: 'አንዳንድ ጊዜ አነባለሁ', category: 'phrase', lesson_id: 43, pronunciation_guide: null },
  { english: 'Wake up early', romanized: 'qedem neka', amharic: 'ቀደም ተነስ', category: 'phrase', lesson_id: 43, pronunciation_guide: null },
  { english: "Don't be late", romanized: 'atizegiy', amharic: 'አትዘግይ', category: 'phrase', lesson_id: 43, pronunciation_guide: null },
  { english: 'Are you ready', romanized: 'tezegejihal', amharic: 'ተዘጋጅተሃል', category: 'phrase', lesson_id: 43, pronunciation_guide: null },
  { english: 'I am busy', romanized: 'isir neñ', amharic: 'ዝብርቅርቅ ነኝ', category: 'phrase', lesson_id: 43, pronunciation_guide: null },
  { english: 'No problem', romanized: 'chigir yelem', amharic: 'ችግር የለም', category: 'phrase', lesson_id: 43, pronunciation_guide: null },
  { english: 'What is the answer', romanized: 'melsu min new', amharic: 'መልሱ ምን ነው', category: 'phrase', lesson_id: 43, pronunciation_guide: null },
  { english: 'I have a question', romanized: 'tiyaqe aleñ', amharic: 'ጥያቄ አለኝ', category: 'phrase', lesson_id: 43, pronunciation_guide: null },
  { english: 'Good idea', romanized: 'tiru hasab', amharic: 'ጥሩ ሃሳብ', category: 'phrase', lesson_id: 43, pronunciation_guide: null },
  { english: 'What is the plan', romanized: 'iqidu min new', amharic: 'ዕቅዱ ምን ነው', category: 'phrase', lesson_id: 43, pronunciation_guide: null },
  { english: 'I am sure', romanized: 'irgiṭegna neñ', amharic: 'እርግጠኛ ነኝ', category: 'phrase', lesson_id: 43, pronunciation_guide: null },
  { english: 'Maybe tomorrow', romanized: 'minaibat nege', amharic: 'ምናልባት ነገ', category: 'phrase', lesson_id: 43, pronunciation_guide: null },
  { english: "Let's go together", romanized: 'beyiberet inihid', amharic: 'በጋራ እንሂድ', category: 'phrase', lesson_id: 43, pronunciation_guide: null },
  { english: 'I am alone', romanized: 'bichaye neñ', amharic: 'ብቻዬ ነኝ', category: 'phrase', lesson_id: 43, pronunciation_guide: null },
  { english: 'That is enough', romanized: 'beqi new', amharic: 'በቂ ነው', category: 'phrase', lesson_id: 43, pronunciation_guide: null },
];
