export const vocabPart1 = [
  // ============================================================
  // LESSON 29: Body Parts (Unit 6: Vocabulary Expansion)
  // ============================================================

  // -- Words (20 nouns) --
  { english: 'head', romanized: 'ras', amharic: 'ራስ', category: 'noun', lesson_id: 29, pronunciation_guide: null },
  { english: 'eye', romanized: 'ayn', amharic: 'ዓይን', category: 'noun', lesson_id: 29, pronunciation_guide: null },
  { english: 'ear', romanized: 'joro', amharic: 'ጆሮ', category: 'noun', lesson_id: 29, pronunciation_guide: null },
  { english: 'nose', romanized: 'afncha', amharic: 'አፍንጫ', category: 'noun', lesson_id: 29, pronunciation_guide: null },
  { english: 'mouth', romanized: 'af', amharic: 'አፍ', category: 'noun', lesson_id: 29, pronunciation_guide: null },
  { english: 'hand', romanized: 'ij', amharic: 'እጅ', category: 'noun', lesson_id: 29, pronunciation_guide: null },
  { english: 'foot', romanized: 'igr', amharic: 'እግር', category: 'noun', lesson_id: 29, pronunciation_guide: null },
  { english: 'finger', romanized: 'tat', amharic: 'ጣት', category: 'noun', lesson_id: 29, pronunciation_guide: null },
  { english: 'hair', romanized: 'tsegur', amharic: 'ጸጉር', category: 'noun', lesson_id: 29, pronunciation_guide: null },
  { english: 'face', romanized: 'fit', amharic: 'ፊት', category: 'noun', lesson_id: 29, pronunciation_guide: null },
  { english: 'tooth', romanized: 'tirs', amharic: 'ጥርስ', category: 'noun', lesson_id: 29, pronunciation_guide: null },
  { english: 'tongue', romanized: 'milas', amharic: 'ምላስ', category: 'noun', lesson_id: 29, pronunciation_guide: null },
  { english: 'neck', romanized: 'angat', amharic: 'አንገት', category: 'noun', lesson_id: 29, pronunciation_guide: null },
  { english: 'back', romanized: 'jerba', amharic: 'ጀርባ', category: 'noun', lesson_id: 29, pronunciation_guide: null },
  { english: 'stomach', romanized: 'hod', amharic: 'ሆድ', category: 'noun', lesson_id: 29, pronunciation_guide: null },
  { english: 'heart', romanized: 'lib', amharic: 'ልብ', category: 'noun', lesson_id: 29, pronunciation_guide: null },
  { english: 'blood', romanized: 'dem', amharic: 'ደም', category: 'noun', lesson_id: 29, pronunciation_guide: null },
  { english: 'bone', romanized: 'atint', amharic: 'አጥንት', category: 'noun', lesson_id: 29, pronunciation_guide: null },
  { english: 'skin', romanized: 'qoda', amharic: 'ቆዳ', category: 'noun', lesson_id: 29, pronunciation_guide: null },
  { english: 'shoulder', romanized: 'tiksha', amharic: 'ትከሻ', category: 'noun', lesson_id: 29, pronunciation_guide: null },

  // -- Phrases (20) --
  { english: 'My head hurts', romanized: 'rase yamenal', amharic: 'ራሴ ያመኛል', category: 'phrase', lesson_id: 29, pronunciation_guide: null },
  { english: 'Wash your hands', romanized: 'ijhin tateb', amharic: 'እጅህን ታጠብ', category: 'phrase', lesson_id: 29, pronunciation_guide: null },
  { english: 'Open your eyes', romanized: 'aynihin kfet', amharic: 'ዓይንህን ክፈት', category: 'phrase', lesson_id: 29, pronunciation_guide: null },
  { english: 'I have a toothache', romanized: 'tirse yamenal', amharic: 'ጥርሴ ያመኛል', category: 'phrase', lesson_id: 29, pronunciation_guide: null },
  { english: 'My stomach hurts', romanized: 'hode yamenal', amharic: 'ሆዴ ያመኛል', category: 'phrase', lesson_id: 29, pronunciation_guide: null },
  { english: 'Close your mouth', romanized: 'afihin zga', amharic: 'አፍህን ዝጋ', category: 'phrase', lesson_id: 29, pronunciation_guide: null },
  { english: 'My back hurts', romanized: 'jerbaye yamenal', amharic: 'ጀርባዬ ያመኛል', category: 'phrase', lesson_id: 29, pronunciation_guide: null },
  { english: 'Give me your hand', romanized: 'ijihin sten', amharic: 'እጅህን ስጠኝ', category: 'phrase', lesson_id: 29, pronunciation_guide: null },
  { english: 'I cannot hear', romanized: 'mesmat alchilim', amharic: 'መስማት አልችልም', category: 'phrase', lesson_id: 29, pronunciation_guide: null },
  { english: 'She has long hair', romanized: 'rejim tsegur alat', amharic: 'ረጅም ጸጉር አላት', category: 'phrase', lesson_id: 29, pronunciation_guide: null },
  { english: 'My neck hurts', romanized: 'angate yamenal', amharic: 'አንገቴ ያመኛል', category: 'phrase', lesson_id: 29, pronunciation_guide: null },
  { english: 'The blood is red', romanized: 'demu qey new', amharic: 'ደሙ ቀይ ነው', category: 'phrase', lesson_id: 29, pronunciation_guide: null },
  { english: 'My heart is strong', romanized: 'libe tenkara new', amharic: 'ልቤ ጠንካራ ነው', category: 'phrase', lesson_id: 29, pronunciation_guide: null },
  { english: 'Stand on your feet', romanized: 'beigrih qum', amharic: 'በእግርህ ቁም', category: 'phrase', lesson_id: 29, pronunciation_guide: null },
  { english: 'My skin is dry', romanized: 'qodaye derek new', amharic: 'ቆዳዬ ደረቅ ነው', category: 'phrase', lesson_id: 29, pronunciation_guide: null },
  { english: 'The bone is broken', romanized: 'atintu tesebere', amharic: 'አጥንቱ ተሰበረ', category: 'phrase', lesson_id: 29, pronunciation_guide: null },
  { english: 'I feel pain', romanized: 'himemin yisemanal', amharic: 'ህመም ይሰማኛል', category: 'phrase', lesson_id: 29, pronunciation_guide: null },
  { english: 'Touch your face', romanized: 'fitihin nka', amharic: 'ፊትህን ንካ', category: 'phrase', lesson_id: 29, pronunciation_guide: null },
  { english: 'Raise your hand', romanized: 'ijihin anusa', amharic: 'እጅህን አንሳ', category: 'phrase', lesson_id: 29, pronunciation_guide: null },
  { english: 'Turn your head', romanized: 'rasihin azur', amharic: 'ራስህን አዙር', category: 'phrase', lesson_id: 29, pronunciation_guide: null },

  // ============================================================
  // LESSON 30: Animals (Unit 6: Vocabulary Expansion)
  // ============================================================

  // -- Words (20 nouns) --
  { english: 'dog', romanized: 'wusha', amharic: 'ውሻ', category: 'noun', lesson_id: 30, pronunciation_guide: null },
  { english: 'cat', romanized: 'dmet', amharic: 'ድመት', category: 'noun', lesson_id: 30, pronunciation_guide: null },
  { english: 'cow', romanized: 'lam', amharic: 'ላም', category: 'noun', lesson_id: 30, pronunciation_guide: null },
  { english: 'horse', romanized: 'feres', amharic: 'ፈረስ', category: 'noun', lesson_id: 30, pronunciation_guide: null },
  { english: 'donkey', romanized: 'ahiya', amharic: 'አህያ', category: 'noun', lesson_id: 30, pronunciation_guide: null },
  { english: 'sheep', romanized: 'beg', amharic: 'በግ', category: 'noun', lesson_id: 30, pronunciation_guide: null },
  { english: 'goat', romanized: 'fiyel', amharic: 'ፍየል', category: 'noun', lesson_id: 30, pronunciation_guide: null },
  { english: 'chicken', romanized: 'doro', amharic: 'ዶሮ', category: 'noun', lesson_id: 30, pronunciation_guide: null },
  { english: 'bird', romanized: 'wof', amharic: 'ወፍ', category: 'noun', lesson_id: 30, pronunciation_guide: null },
  { english: 'fish', romanized: 'asa', amharic: 'ዓሳ', category: 'noun', lesson_id: 30, pronunciation_guide: null },
  { english: 'lion', romanized: 'anbessa', amharic: 'አንበሳ', category: 'noun', lesson_id: 30, pronunciation_guide: null },
  { english: 'monkey', romanized: 'zinjero', amharic: 'ዝንጀሮ', category: 'noun', lesson_id: 30, pronunciation_guide: null },
  { english: 'snake', romanized: 'ibab', amharic: 'እባብ', category: 'noun', lesson_id: 30, pronunciation_guide: null },
  { english: 'elephant', romanized: 'zihon', amharic: 'ዝሆን', category: 'noun', lesson_id: 30, pronunciation_guide: null },
  { english: 'camel', romanized: 'gimel', amharic: 'ግመል', category: 'noun', lesson_id: 30, pronunciation_guide: null },
  { english: 'bee', romanized: 'nib', amharic: 'ንብ', category: 'noun', lesson_id: 30, pronunciation_guide: null },
  { english: 'rabbit', romanized: 'tinchel', amharic: 'ጥንቸል', category: 'noun', lesson_id: 30, pronunciation_guide: null },
  { english: 'hyena', romanized: 'jib', amharic: 'ጅብ', category: 'noun', lesson_id: 30, pronunciation_guide: null },
  { english: 'mouse', romanized: 'ayt', amharic: 'አይጥ', category: 'noun', lesson_id: 30, pronunciation_guide: null },
  { english: 'ox', romanized: 'bere', amharic: 'በሬ', category: 'noun', lesson_id: 30, pronunciation_guide: null },

  // -- Phrases (20) --
  { english: 'I have a dog', romanized: 'wusha alen', amharic: 'ውሻ አለኝ', category: 'phrase', lesson_id: 30, pronunciation_guide: null },
  { english: 'The cat is sleeping', romanized: 'dmetua tentowal', amharic: 'ድመቷ ተኝታለች', category: 'phrase', lesson_id: 30, pronunciation_guide: null },
  { english: 'The cow gives milk', romanized: 'lamiwa wetat tsetalech', amharic: 'ላሚዋ ወተት ትሰጣለች', category: 'phrase', lesson_id: 30, pronunciation_guide: null },
  { english: 'The horse is fast', romanized: 'feresu fetena new', amharic: 'ፈረሱ ፈጣና ነው', category: 'phrase', lesson_id: 30, pronunciation_guide: null },
  { english: 'The donkey is strong', romanized: 'ahiyaw tenkara new', amharic: 'አህያው ጠንካራ ነው', category: 'phrase', lesson_id: 30, pronunciation_guide: null },
  { english: 'I like birds', romanized: 'wof iwedallehu', amharic: 'ወፍ እወዳለሁ', category: 'phrase', lesson_id: 30, pronunciation_guide: null },
  { english: 'The fish is in the water', romanized: 'asau bewuha wist new', amharic: 'ዓሳው በውሃ ውስጥ ነው', category: 'phrase', lesson_id: 30, pronunciation_guide: null },
  { english: 'The lion is the king', romanized: 'anbessa ye-enssat nigus new', amharic: 'አንበሳ የእንስሳት ንጉሥ ነው', category: 'phrase', lesson_id: 30, pronunciation_guide: null },
  { english: 'The snake is dangerous', romanized: 'ibab adegegna new', amharic: 'እባብ አደገኛ ነው', category: 'phrase', lesson_id: 30, pronunciation_guide: null },
  { english: 'The elephant is big', romanized: 'zihonu tillik new', amharic: 'ዝሆኑ ትልቅ ነው', category: 'phrase', lesson_id: 30, pronunciation_guide: null },
  { english: 'The bee makes honey', romanized: 'nibu mar yiserawal', amharic: 'ንቡ ማር ይሠራል', category: 'phrase', lesson_id: 30, pronunciation_guide: null },
  { english: 'The monkey is clever', romanized: 'zinjerow gobez new', amharic: 'ዝንጀሮው ጎበዝ ነው', category: 'phrase', lesson_id: 30, pronunciation_guide: null },
  { english: 'The rabbit is small', romanized: 'tinchelu tinish new', amharic: 'ጥንቸሉ ትንሽ ነው', category: 'phrase', lesson_id: 30, pronunciation_guide: null },
  { english: 'The hyena comes at night', romanized: 'jibu bemata yimetal', amharic: 'ጅቡ በማታ ይመጣል', category: 'phrase', lesson_id: 30, pronunciation_guide: null },
  { english: 'I am afraid of snakes', romanized: 'ibab yiferanal', amharic: 'እባብ ይፈራኛል', category: 'phrase', lesson_id: 30, pronunciation_guide: null },
  { english: 'She has a pet cat', romanized: 'yeras dmet alat', amharic: 'የራሷ ድመት አላት', category: 'phrase', lesson_id: 30, pronunciation_guide: null },
  { english: 'The dog is barking', romanized: 'wushau yijohall', amharic: 'ውሻው ይጮሃል', category: 'phrase', lesson_id: 30, pronunciation_guide: null },
  { english: 'Feed the chicken', romanized: 'doroun amgbi', amharic: 'ዶሮውን አምግቢ', category: 'phrase', lesson_id: 30, pronunciation_guide: null },
  { english: 'The sheep is white', romanized: 'begu nech new', amharic: 'በጉ ነጭ ነው', category: 'phrase', lesson_id: 30, pronunciation_guide: null },
  { english: 'The camel is in the desert', romanized: 'gimelu bemidaber new', amharic: 'ግመሉ በምድረ በዳ ነው', category: 'phrase', lesson_id: 30, pronunciation_guide: null },

  // ============================================================
  // LESSON 31: Colors & Descriptions (Unit 6: Vocabulary Expansion)
  // ============================================================

  // -- Words (20 adjectives) --
  { english: 'red', romanized: 'qey', amharic: 'ቀይ', category: 'adjective', lesson_id: 31, pronunciation_guide: null },
  { english: 'blue', romanized: 'semayawi', amharic: 'ሰማያዊ', category: 'adjective', lesson_id: 31, pronunciation_guide: null },
  { english: 'green', romanized: 'arenguade', amharic: 'አረንጓዴ', category: 'adjective', lesson_id: 31, pronunciation_guide: null },
  { english: 'yellow', romanized: 'bicha', amharic: 'ቢጫ', category: 'adjective', lesson_id: 31, pronunciation_guide: null },
  { english: 'white', romanized: 'nech', amharic: 'ነጭ', category: 'adjective', lesson_id: 31, pronunciation_guide: null },
  { english: 'black', romanized: 'tikur', amharic: 'ጥቁር', category: 'adjective', lesson_id: 31, pronunciation_guide: null },
  { english: 'brown', romanized: 'bunama', amharic: 'ቡናማ', category: 'adjective', lesson_id: 31, pronunciation_guide: null },
  { english: 'orange', romanized: 'birtukana', amharic: 'ብርቱካናማ', category: 'adjective', lesson_id: 31, pronunciation_guide: null },
  { english: 'purple', romanized: 'hamrawi', amharic: 'ሐምራዊ', category: 'adjective', lesson_id: 31, pronunciation_guide: null },
  { english: 'gray', romanized: 'gracha', amharic: 'ግራጫ', category: 'adjective', lesson_id: 31, pronunciation_guide: null },
  { english: 'big', romanized: 'tillik', amharic: 'ትልቅ', category: 'adjective', lesson_id: 31, pronunciation_guide: null },
  { english: 'small', romanized: 'tinish', amharic: 'ትንሽ', category: 'adjective', lesson_id: 31, pronunciation_guide: null },
  { english: 'tall', romanized: 'rejim', amharic: 'ረጅም', category: 'adjective', lesson_id: 31, pronunciation_guide: null },
  { english: 'short', romanized: 'achir', amharic: 'አጭር', category: 'adjective', lesson_id: 31, pronunciation_guide: null },
  { english: 'long', romanized: 'rejim', amharic: 'ረጅም', category: 'adjective', lesson_id: 31, pronunciation_guide: null },
  { english: 'heavy', romanized: 'kebad', amharic: 'ከባድ', category: 'adjective', lesson_id: 31, pronunciation_guide: null },
  { english: 'light (weight)', romanized: 'qelal', amharic: 'ቀላል', category: 'adjective', lesson_id: 31, pronunciation_guide: null },
  { english: 'new', romanized: 'adis', amharic: 'አዲስ', category: 'adjective', lesson_id: 31, pronunciation_guide: null },
  { english: 'old', romanized: 'aroge', amharic: 'አሮጌ', category: 'adjective', lesson_id: 31, pronunciation_guide: null },
  { english: 'beautiful', romanized: 'qonjo', amharic: 'ቆንጆ', category: 'adjective', lesson_id: 31, pronunciation_guide: null },

  // -- Phrases (20) --
  { english: 'What color is this', romanized: 'yih min qelem new', amharic: 'ይህ ምን ቀለም ነው', category: 'phrase', lesson_id: 31, pronunciation_guide: null },
  { english: 'The sky is blue', romanized: 'semay semayawi new', amharic: 'ሰማይ ሰማያዊ ነው', category: 'phrase', lesson_id: 31, pronunciation_guide: null },
  { english: 'The grass is green', romanized: 'saru arenguade new', amharic: 'ሣሩ አረንጓዴ ነው', category: 'phrase', lesson_id: 31, pronunciation_guide: null },
  { english: 'The sun is yellow', romanized: 'tsehay bicha new', amharic: 'ፀሐይ ቢጫ ነው', category: 'phrase', lesson_id: 31, pronunciation_guide: null },
  { english: 'My shirt is white', romanized: 'shemize nech new', amharic: 'ሸሚዜ ነጭ ነው', category: 'phrase', lesson_id: 31, pronunciation_guide: null },
  { english: 'The night is black', romanized: 'matau tikur new', amharic: 'ማታው ጥቁር ነው', category: 'phrase', lesson_id: 31, pronunciation_guide: null },
  { english: 'I like red', romanized: 'qey iwedalehu', amharic: 'ቀይ እወዳለሁ', category: 'phrase', lesson_id: 31, pronunciation_guide: null },
  { english: 'This is big', romanized: 'yih tillik new', amharic: 'ይህ ትልቅ ነው', category: 'phrase', lesson_id: 31, pronunciation_guide: null },
  { english: 'This is small', romanized: 'yih tinish new', amharic: 'ይህ ትንሽ ነው', category: 'phrase', lesson_id: 31, pronunciation_guide: null },
  { english: 'He is tall', romanized: 'irsu rejim new', amharic: 'እርሱ ረጅም ነው', category: 'phrase', lesson_id: 31, pronunciation_guide: null },
  { english: 'She is short', romanized: 'irsua achir nat', amharic: 'እርሷ አጭር ናት', category: 'phrase', lesson_id: 31, pronunciation_guide: null },
  { english: 'This bag is heavy', romanized: 'yih borsaa kebad new', amharic: 'ይህ ቦርሳ ከባድ ነው', category: 'phrase', lesson_id: 31, pronunciation_guide: null },
  { english: 'This is light', romanized: 'yih qelal new', amharic: 'ይህ ቀላል ነው', category: 'phrase', lesson_id: 31, pronunciation_guide: null },
  { english: 'I bought new shoes', romanized: 'adis chama gezehu', amharic: 'አዲስ ጫማ ገዛሁ', category: 'phrase', lesson_id: 31, pronunciation_guide: null },
  { english: 'This is old', romanized: 'yih aroge new', amharic: 'ይህ አሮጌ ነው', category: 'phrase', lesson_id: 31, pronunciation_guide: null },
  { english: 'She is beautiful', romanized: 'irsua qonjo nat', amharic: 'እርሷ ቆንጆ ናት', category: 'phrase', lesson_id: 31, pronunciation_guide: null },
  { english: 'The coffee is brown', romanized: 'bunaw bunama new', amharic: 'ቡናው ቡናማ ነው', category: 'phrase', lesson_id: 31, pronunciation_guide: null },
  { english: 'The flower is purple', romanized: 'ababau hamrawi new', amharic: 'አበባው ሐምራዊ ነው', category: 'phrase', lesson_id: 31, pronunciation_guide: null },
  { english: 'My hair is black', romanized: 'tsegure tikur new', amharic: 'ጸጉሬ ጥቁር ነው', category: 'phrase', lesson_id: 31, pronunciation_guide: null },
  { english: 'The house is big', romanized: 'betu tillik new', amharic: 'ቤቱ ትልቅ ነው', category: 'phrase', lesson_id: 31, pronunciation_guide: null },

  // ============================================================
  // LESSON 32: Food & Ingredients (Unit 6: Vocabulary Expansion)
  // ============================================================

  // -- Words (20 nouns) --
  { english: 'bread', romanized: 'dabo', amharic: 'ዳቦ', category: 'noun', lesson_id: 32, pronunciation_guide: null },
  { english: 'injera', romanized: 'injera', amharic: 'እንጀራ', category: 'noun', lesson_id: 32, pronunciation_guide: null },
  { english: 'meat', romanized: 'siga', amharic: 'ስጋ', category: 'noun', lesson_id: 32, pronunciation_guide: null },
  { english: 'egg', romanized: 'inqulal', amharic: 'እንቁላል', category: 'noun', lesson_id: 32, pronunciation_guide: null },
  { english: 'butter', romanized: 'qibe', amharic: 'ቅቤ', category: 'noun', lesson_id: 32, pronunciation_guide: null },
  { english: 'honey', romanized: 'mar', amharic: 'ማር', category: 'noun', lesson_id: 32, pronunciation_guide: null },
  { english: 'salt', romanized: 'chew', amharic: 'ጨው', category: 'noun', lesson_id: 32, pronunciation_guide: null },
  { english: 'pepper/spice', romanized: 'berbere', amharic: 'በርበሬ', category: 'noun', lesson_id: 32, pronunciation_guide: null },
  { english: 'onion', romanized: 'shinkurt', amharic: 'ሽንኩርት', category: 'noun', lesson_id: 32, pronunciation_guide: null },
  { english: 'tomato', romanized: 'timatim', amharic: 'ቲማቲም', category: 'noun', lesson_id: 32, pronunciation_guide: null },
  { english: 'potato', romanized: 'dinich', amharic: 'ድንች', category: 'noun', lesson_id: 32, pronunciation_guide: null },
  { english: 'banana', romanized: 'muz', amharic: 'ሙዝ', category: 'noun', lesson_id: 32, pronunciation_guide: null },
  { english: 'orange (fruit)', romanized: 'birtukan', amharic: 'ብርቱካን', category: 'noun', lesson_id: 32, pronunciation_guide: null },
  { english: 'lemon', romanized: 'lomi', amharic: 'ሎሚ', category: 'noun', lesson_id: 32, pronunciation_guide: null },
  { english: 'rice', romanized: 'ruz', amharic: 'ሩዝ', category: 'noun', lesson_id: 32, pronunciation_guide: null },
  { english: 'sugar', romanized: 'sikwar', amharic: 'ስኳር', category: 'noun', lesson_id: 32, pronunciation_guide: null },
  { english: 'oil', romanized: 'zeyt', amharic: 'ዘይት', category: 'noun', lesson_id: 32, pronunciation_guide: null },
  { english: 'cheese', romanized: 'ayib', amharic: 'አይብ', category: 'noun', lesson_id: 32, pronunciation_guide: null },
  { english: 'lentils', romanized: 'misir', amharic: 'ምስር', category: 'noun', lesson_id: 32, pronunciation_guide: null },
  { english: 'garlic', romanized: 'nech shinkurt', amharic: 'ነጭ ሽንኩርት', category: 'noun', lesson_id: 32, pronunciation_guide: null },

  // -- Phrases (20) --
  { english: 'I am hungry', romanized: 'raben', amharic: 'ራበኝ', category: 'phrase', lesson_id: 32, pronunciation_guide: null },
  { english: 'The food is delicious', romanized: 'migbu tafach new', amharic: 'ምግቡ ጣፋጭ ነው', category: 'phrase', lesson_id: 32, pronunciation_guide: null },
  { english: 'I want injera', romanized: 'injera ifelligalehu', amharic: 'እንጀራ እፈልጋለሁ', category: 'phrase', lesson_id: 32, pronunciation_guide: null },
  { english: 'Please bring bread', romanized: 'dabo amtu', amharic: 'ዳቦ አምጡ', category: 'phrase', lesson_id: 32, pronunciation_guide: null },
  { english: 'The egg is cooked', romanized: 'inqulalu bisle', amharic: 'እንቁላሉ ብስሏል', category: 'phrase', lesson_id: 32, pronunciation_guide: null },
  { english: 'Add more salt', romanized: 'tekemare chew jmr', amharic: 'ተጨማሪ ጨው ጨምር', category: 'phrase', lesson_id: 32, pronunciation_guide: null },
  { english: 'I like honey', romanized: 'mar iwedalehu', amharic: 'ማር እወዳለሁ', category: 'phrase', lesson_id: 32, pronunciation_guide: null },
  { english: 'Cut the onion', romanized: 'shinkurt qretew', amharic: 'ሽንኩርት ቁረጠው', category: 'phrase', lesson_id: 32, pronunciation_guide: null },
  { english: 'The tomato is red', romanized: 'timatim qey new', amharic: 'ቲማቲም ቀይ ነው', category: 'phrase', lesson_id: 32, pronunciation_guide: null },
  { english: 'I want banana', romanized: 'muz ifelligalehu', amharic: 'ሙዝ እፈልጋለሁ', category: 'phrase', lesson_id: 32, pronunciation_guide: null },
  { english: 'Squeeze the lemon', romanized: 'lomiun atsmeqew', amharic: 'ሎሚውን አጭመቀው', category: 'phrase', lesson_id: 32, pronunciation_guide: null },
  { english: 'Cook the rice', romanized: 'ruzu absil', amharic: 'ሩዙን አብስል', category: 'phrase', lesson_id: 32, pronunciation_guide: null },
  { english: 'Too much sugar', romanized: 'besigab sikwar', amharic: 'በጣም ብዙ ስኳር', category: 'phrase', lesson_id: 32, pronunciation_guide: null },
  { english: 'I need oil', romanized: 'zeyt yifeligenal', amharic: 'ዘይት ይፈልጋኛል', category: 'phrase', lesson_id: 32, pronunciation_guide: null },
  { english: 'The cheese is fresh', romanized: 'ayibu tara new', amharic: 'አይቡ ጥራ ነው', category: 'phrase', lesson_id: 32, pronunciation_guide: null },
  { english: 'Lentil stew is tasty', romanized: 'misir wet tafach new', amharic: 'ምስር ወጥ ጣፋጭ ነው', category: 'phrase', lesson_id: 32, pronunciation_guide: null },
  { english: 'Peel the potato', romanized: 'dinichu lafew', amharic: 'ድንቹን ላጠው', category: 'phrase', lesson_id: 32, pronunciation_guide: null },
  { english: 'Mix the berbere', romanized: 'berberew qalaqil', amharic: 'በርበሬውን ቀላቅል', category: 'phrase', lesson_id: 32, pronunciation_guide: null },
  { english: 'The butter melted', romanized: 'qibew qaletew', amharic: 'ቅቤው ቀልጧል', category: 'phrase', lesson_id: 32, pronunciation_guide: null },
  { english: 'Breakfast is ready', romanized: 'qurs tezegaztual', amharic: 'ቁርስ ተዘጋጅቷል', category: 'phrase', lesson_id: 32, pronunciation_guide: null },

  // ============================================================
  // LESSON 33: Drinks & Kitchen (Unit 6: Vocabulary Expansion)
  // ============================================================

  // -- Words (20 nouns) --
  { english: 'water', romanized: 'wuha', amharic: 'ውሃ', category: 'noun', lesson_id: 33, pronunciation_guide: null },
  { english: 'coffee', romanized: 'buna', amharic: 'ቡና', category: 'noun', lesson_id: 33, pronunciation_guide: null },
  { english: 'tea', romanized: 'shai', amharic: 'ሻይ', category: 'noun', lesson_id: 33, pronunciation_guide: null },
  { english: 'milk', romanized: 'wetat', amharic: 'ወተት', category: 'noun', lesson_id: 33, pronunciation_guide: null },
  { english: 'juice', romanized: 'chemaki', amharic: 'ጭማቂ', category: 'noun', lesson_id: 33, pronunciation_guide: null },
  { english: 'cup', romanized: 'siniya', amharic: 'ሲኒ', category: 'noun', lesson_id: 33, pronunciation_guide: null },
  { english: 'plate', romanized: 'sahan', amharic: 'ሳህን', category: 'noun', lesson_id: 33, pronunciation_guide: null },
  { english: 'spoon', romanized: 'mankiya', amharic: 'ማንኪያ', category: 'noun', lesson_id: 33, pronunciation_guide: null },
  { english: 'knife', romanized: 'billa', amharic: 'ቢላ', category: 'noun', lesson_id: 33, pronunciation_guide: null },
  { english: 'fork', romanized: 'shuka', amharic: 'ሹካ', category: 'noun', lesson_id: 33, pronunciation_guide: null },
  { english: 'glass', romanized: 'birchiko', amharic: 'ብርጭቆ', category: 'noun', lesson_id: 33, pronunciation_guide: null },
  { english: 'bottle', romanized: 'termus', amharic: 'ጠርሙስ', category: 'noun', lesson_id: 33, pronunciation_guide: null },
  { english: 'pot', romanized: 'dist', amharic: 'ድስት', category: 'noun', lesson_id: 33, pronunciation_guide: null },
  { english: 'stove', romanized: 'midija', amharic: 'ምድጃ', category: 'noun', lesson_id: 33, pronunciation_guide: null },
  { english: 'fridge', romanized: 'maqezeqeziya', amharic: 'ማቀዝቀዣ', category: 'noun', lesson_id: 33, pronunciation_guide: null },
  { english: 'tray', romanized: 'sini', amharic: 'ሲኒ', category: 'noun', lesson_id: 33, pronunciation_guide: null },
  { english: 'bowl', romanized: 'sahle', amharic: 'ሳህለ', category: 'noun', lesson_id: 33, pronunciation_guide: null },
  { english: 'kettle', romanized: 'jebena', amharic: 'ጀበና', category: 'noun', lesson_id: 33, pronunciation_guide: null },
  { english: 'soap', romanized: 'samuna', amharic: 'ሳሙና', category: 'noun', lesson_id: 33, pronunciation_guide: null },
  { english: 'towel', romanized: 'fota', amharic: 'ፎጣ', category: 'noun', lesson_id: 33, pronunciation_guide: null },

  // -- Phrases (20) --
  { english: 'I want coffee', romanized: 'buna ifelligalehu', amharic: 'ቡና እፈልጋለሁ', category: 'phrase', lesson_id: 33, pronunciation_guide: null },
  { english: 'Please bring water', romanized: 'wuha amtu', amharic: 'ውሃ አምጡ', category: 'phrase', lesson_id: 33, pronunciation_guide: null },
  { english: 'The tea is hot', romanized: 'shayu muq new', amharic: 'ሻዩ ሙቅ ነው', category: 'phrase', lesson_id: 33, pronunciation_guide: null },
  { english: 'Give me milk', romanized: 'wetat sten', amharic: 'ወተት ስጠኝ', category: 'phrase', lesson_id: 33, pronunciation_guide: null },
  { english: 'Pour the juice', romanized: 'chemakiun qda', amharic: 'ጭማቂውን ቅዳ', category: 'phrase', lesson_id: 33, pronunciation_guide: null },
  { english: 'The cup is empty', romanized: 'siniyaw badudu new', amharic: 'ሲኒው ባዶ ነው', category: 'phrase', lesson_id: 33, pronunciation_guide: null },
  { english: 'Wash the plate', romanized: 'sahanu tateb', amharic: 'ሳህኑን ታጠብ', category: 'phrase', lesson_id: 33, pronunciation_guide: null },
  { english: 'I need a spoon', romanized: 'mankiya yifeligenal', amharic: 'ማንኪያ ይፈልጋኛል', category: 'phrase', lesson_id: 33, pronunciation_guide: null },
  { english: 'The knife is sharp', romanized: 'billaw sil new', amharic: 'ቢላው ስል ነው', category: 'phrase', lesson_id: 33, pronunciation_guide: null },
  { english: 'The glass is broken', romanized: 'birchikow tesebere', amharic: 'ብርጭቆው ተሰበረ', category: 'phrase', lesson_id: 33, pronunciation_guide: null },
  { english: 'Fill the bottle', romanized: 'termuzun mla', amharic: 'ጠርሙሱን ሙላ', category: 'phrase', lesson_id: 33, pronunciation_guide: null },
  { english: 'Put on the stove', romanized: 'midija lay asqemit', amharic: 'ምድጃ ላይ አስቀምጥ', category: 'phrase', lesson_id: 33, pronunciation_guide: null },
  { english: 'Open the fridge', romanized: 'maqezeqeziyan kfet', amharic: 'ማቀዝቀዣውን ክፈት', category: 'phrase', lesson_id: 33, pronunciation_guide: null },
  { english: 'Make coffee with jebena', romanized: 'bejebena buna asera', amharic: 'በጀበና ቡና አሠራ', category: 'phrase', lesson_id: 33, pronunciation_guide: null },
  { english: 'The water is cold', romanized: 'wuhaw qezqaza new', amharic: 'ውሃው ቀዝቃዛ ነው', category: 'phrase', lesson_id: 33, pronunciation_guide: null },
  { english: 'Dry with a towel', romanized: 'befota adriq', amharic: 'በፎጣ አድርቅ', category: 'phrase', lesson_id: 33, pronunciation_guide: null },
  { english: 'I am thirsty', romanized: 'teman', amharic: 'ጠማኝ', category: 'phrase', lesson_id: 33, pronunciation_guide: null },
  { english: 'Boil the water', romanized: 'wuhan afla', amharic: 'ውሃውን አፍላ', category: 'phrase', lesson_id: 33, pronunciation_guide: null },
  { english: 'The pot is on the fire', romanized: 'distu beisat lay new', amharic: 'ድስቱ በእሳት ላይ ነው', category: 'phrase', lesson_id: 33, pronunciation_guide: null },
  { english: 'Use soap to wash', romanized: 'besamuna tateb', amharic: 'በሳሙና ታጠብ', category: 'phrase', lesson_id: 33, pronunciation_guide: null },

  // ============================================================
  // LESSON 34: Clothing & Accessories (Unit 6: Vocabulary Expansion)
  // ============================================================

  // -- Words (20 nouns) --
  { english: 'shirt', romanized: 'shemiz', amharic: 'ሸሚዝ', category: 'noun', lesson_id: 34, pronunciation_guide: null },
  { english: 'pants', romanized: 'suri', amharic: 'ሱሪ', category: 'noun', lesson_id: 34, pronunciation_guide: null },
  { english: 'shoes', romanized: 'chama', amharic: 'ጫማ', category: 'noun', lesson_id: 34, pronunciation_guide: null },
  { english: 'dress', romanized: 'qemis', amharic: 'ቀሚስ', category: 'noun', lesson_id: 34, pronunciation_guide: null },
  { english: 'hat', romanized: 'kofiya', amharic: 'ኮፍያ', category: 'noun', lesson_id: 34, pronunciation_guide: null },
  { english: 'scarf', romanized: 'netela', amharic: 'ነጠላ', category: 'noun', lesson_id: 34, pronunciation_guide: null },
  { english: 'belt', romanized: 'qebeto', amharic: 'ቀበቶ', category: 'noun', lesson_id: 34, pronunciation_guide: null },
  { english: 'jacket', romanized: 'jaket', amharic: 'ጃኬት', category: 'noun', lesson_id: 34, pronunciation_guide: null },
  { english: 'socks', romanized: 'kalsi', amharic: 'ካልሲ', category: 'noun', lesson_id: 34, pronunciation_guide: null },
  { english: 'clothes', romanized: 'libs', amharic: 'ልብስ', category: 'noun', lesson_id: 34, pronunciation_guide: null },
  { english: 'ring', romanized: 'qelebet', amharic: 'ቀለበት', category: 'noun', lesson_id: 34, pronunciation_guide: null },
  { english: 'watch', romanized: "se'at", amharic: 'ሰዓት', category: 'noun', lesson_id: 34, pronunciation_guide: null },
  { english: 'glasses', romanized: 'menetser', amharic: 'መነጽር', category: 'noun', lesson_id: 34, pronunciation_guide: null },
  { english: 'umbrella', romanized: 'jantila', amharic: 'ጃንጥላ', category: 'noun', lesson_id: 34, pronunciation_guide: null },
  { english: 'bag', romanized: 'borsa', amharic: 'ቦርሳ', category: 'noun', lesson_id: 34, pronunciation_guide: null },
  { english: 'pocket', romanized: 'kise', amharic: 'ኪስ', category: 'noun', lesson_id: 34, pronunciation_guide: null },
  { english: 'button', romanized: 'qulifit', amharic: 'ቁልፊት', category: 'noun', lesson_id: 34, pronunciation_guide: null },
  { english: 'cotton', romanized: 'tit', amharic: 'ጥጥ', category: 'noun', lesson_id: 34, pronunciation_guide: null },
  { english: 'thread', romanized: 'kir', amharic: 'ክር', category: 'noun', lesson_id: 34, pronunciation_guide: null },
  { english: 'needle', romanized: 'merfe', amharic: 'መርፌ', category: 'noun', lesson_id: 34, pronunciation_guide: null },

  // -- Phrases (20) --
  { english: 'I need new shoes', romanized: 'adis chama ifelligalehu', amharic: 'አዲስ ጫማ እፈልጋለሁ', category: 'phrase', lesson_id: 34, pronunciation_guide: null },
  { english: 'Put on your jacket', romanized: 'jakethin libes', amharic: 'ጃኬትህን ልበስ', category: 'phrase', lesson_id: 34, pronunciation_guide: null },
  { english: 'Take off your hat', romanized: 'kofiyahin awliq', amharic: 'ኮፍያህን አውልቅ', category: 'phrase', lesson_id: 34, pronunciation_guide: null },
  { english: 'This dress is beautiful', romanized: 'yih qemis qonjo new', amharic: 'ይህ ቀሚስ ቆንጆ ነው', category: 'phrase', lesson_id: 34, pronunciation_guide: null },
  { english: 'Where are my socks', romanized: 'kalsiye yetno new', amharic: 'ካልሲዬ የት ነው', category: 'phrase', lesson_id: 34, pronunciation_guide: null },
  { english: 'The belt is tight', romanized: 'qebetow yitsbebal', amharic: 'ቀበቶው ይጠብባል', category: 'phrase', lesson_id: 34, pronunciation_guide: null },
  { english: 'Wear warm clothes', romanized: 'muq libs libes', amharic: 'ሙቅ ልብስ ልበስ', category: 'phrase', lesson_id: 34, pronunciation_guide: null },
  { english: 'My bag is full', romanized: 'borsaye moltual', amharic: 'ቦርሳዬ ሞልቷል', category: 'phrase', lesson_id: 34, pronunciation_guide: null },
  { english: 'I lost my umbrella', romanized: 'jantilayen afadehu', amharic: 'ጃንጥላዬን አጣሁ', category: 'phrase', lesson_id: 34, pronunciation_guide: null },
  { english: 'Iron the shirt', romanized: 'shemizun atskye', amharic: 'ሸሚዙን አጥቀሽ', category: 'phrase', lesson_id: 34, pronunciation_guide: null },
  { english: 'These pants are long', romanized: 'yih suri rejim new', amharic: 'ይህ ሱሪ ረጅም ነው', category: 'phrase', lesson_id: 34, pronunciation_guide: null },
  { english: 'Buy me a ring', romanized: 'qelebet gzalin', amharic: 'ቀለበት ግዛልኝ', category: 'phrase', lesson_id: 34, pronunciation_guide: null },
  { english: 'What time is it', romanized: "sint se'at new", amharic: 'ስንት ሰዓት ነው', category: 'phrase', lesson_id: 34, pronunciation_guide: null },
  { english: 'I wear glasses', romanized: 'menetser iqemalehu', amharic: 'መነጽር እቀማለሁ', category: 'phrase', lesson_id: 34, pronunciation_guide: null },
  { english: 'My pocket has a hole', romanized: 'kise qadadewn new', amharic: 'ኪሴ ቀዳዳ ነው', category: 'phrase', lesson_id: 34, pronunciation_guide: null },
  { english: 'Sew the button', romanized: 'qulifit sfa', amharic: 'ቁልፊት ስፋ', category: 'phrase', lesson_id: 34, pronunciation_guide: null },
  { english: 'The netela is white', romanized: 'netelawa nech new', amharic: 'ነጠላው ነጭ ነው', category: 'phrase', lesson_id: 34, pronunciation_guide: null },
  { english: 'Wash the clothes', romanized: 'libsu ateb', amharic: 'ልብሱን አጠብ', category: 'phrase', lesson_id: 34, pronunciation_guide: null },
  { english: 'The shirt is torn', romanized: 'shemizu teqedo', amharic: 'ሸሚዙ ተቀዶ', category: 'phrase', lesson_id: 34, pronunciation_guide: null },
  { english: 'Fold the clothes', romanized: 'libsu atef', amharic: 'ልብሱን አጥፍ', category: 'phrase', lesson_id: 34, pronunciation_guide: null },
];
